"""Deterministic local proof and experiment artifact intake."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from factori.artifacts import ArtifactStore
from factori.full_paper_generation import (
    build_reviewer_bundle_summary,
    render_reviewer_bundle_summary_markdown,
)
from factori.ledger import ResearchLedger
from factori.persistence import (
    ArtifactWriteSpec,
    PersistenceResult,
    persist_artifacts_with_commit,
)
from factori.schemas import (
    ArtifactRef,
    ArtifactType,
    ControllerActionType,
    ExperimentArtifact,
    ProofArtifact,
)

_FORMAL_PROOF_TYPES = {"lean_verified", "formal_verified", "external_certificate"}
_INFORMAL_PROOF_TYPES = {"informal_proof_note", "proof_plan"}
_FORBIDDEN_AUTHORITY_PHRASES = (
    "publication ready",
    "publication-ready",
    "ready for publication",
    "ready to submit",
    "approved for publication",
    "scientifically validated",
    "scientific validation is established",
    "novelty confirmed",
    "novelty validated",
    "correctness validated",
    "correctness is established",
    "paper is correct",
    "proves the paper",
    "validates the paper",
)
_PROOF_VERIFICATION_PHRASES = (
    "proof verified",
    "proof is verified",
    "formally verified",
    "formal verification passed",
)
_EXPERIMENT_VALIDATION_PHRASES = (
    "experiment validated",
    "experiment is validated",
    "empirically validated",
    "broad empirical validation",
    "exhaustive empirical validation",
)
_LLM_GENERATED_MARKERS = (
    "as an ai language model",
    "llm-generated",
    "generated by an llm",
    "generated by ai",
)


class EvidenceArtifactIntakeError(RuntimeError):
    """Raised when proof or experiment artifact intake is unsafe."""


@dataclass(frozen=True)
class ProofArtifactIngestResult:
    """Persisted proof artifact and refreshed reviewer summary."""

    run_id: str
    proof: ProofArtifact
    persistence: PersistenceResult
    proof_artifact: ArtifactRef
    proof_index_artifact: ArtifactRef
    reviewer_summary_artifact: ArtifactRef
    reviewer_summary_markdown_artifact: ArtifactRef


@dataclass(frozen=True)
class ExperimentArtifactIngestResult:
    """Persisted experiment artifact and refreshed reviewer summary."""

    run_id: str
    experiment: ExperimentArtifact
    persistence: PersistenceResult
    experiment_artifact: ArtifactRef
    experiment_index_artifact: ArtifactRef
    reviewer_summary_artifact: ArtifactRef
    reviewer_summary_markdown_artifact: ArtifactRef


def load_proof_artifact(proof_file: str | Path) -> ProofArtifact:
    """Load and structurally validate one local proof artifact JSON file."""
    path = Path(proof_file)
    try:
        return ProofArtifact.model_validate_json(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise EvidenceArtifactIntakeError(f"Unable to read proof file: {path}") from exc
    except ValidationError as exc:
        raise EvidenceArtifactIntakeError(f"Invalid proof artifact: {exc}") from exc


def load_experiment_artifact(experiment_file: str | Path) -> ExperimentArtifact:
    """Load and structurally validate one local experiment artifact JSON file."""
    path = Path(experiment_file)
    try:
        return ExperimentArtifact.model_validate_json(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise EvidenceArtifactIntakeError(
            f"Unable to read experiment file: {path}"
        ) from exc
    except ValidationError as exc:
        raise EvidenceArtifactIntakeError(f"Invalid experiment artifact: {exc}") from exc


def ingest_proof_artifact(
    *,
    run_id: str,
    root: str | Path,
    store: ArtifactStore,
    ledger: ResearchLedger,
    proof_file: str | Path,
) -> ProofArtifactIngestResult:
    """Validate and persist a local proof artifact without readiness upgrades."""
    root_path = Path(root)
    proof = load_proof_artifact(proof_file)
    _validate_proof_artifact(run_id=run_id, root=root_path, proof=proof)
    existing = _load_proof_artifacts(run_id=run_id, root=root_path)
    if any(item.proof_id == proof.proof_id for item in existing):
        raise EvidenceArtifactIntakeError(
            f"proof artifact already exists for proof_id={proof.proof_id}"
        )

    proof_artifact_id = f"proof-artifact-{_safe_suffix(proof.proof_id)}"
    proof_artifact_path = _report_path(run_id, proof_artifact_id)
    proof_index_id = f"proof-artifact-index-{len(_proof_index_paths(root_path, run_id)) + 1:04d}"
    reviewer_summary_id = _next_evidence_reviewer_summary_id(root_path, run_id)
    reviewer_summary = build_reviewer_bundle_summary(
        run_id=run_id,
        root=root_path,
        additional_proof_artifacts=[proof],
        additional_proof_artifact_paths=[proof_artifact_path],
    )
    reviewer_summary_markdown = render_reviewer_bundle_summary_markdown(
        reviewer_summary
    )
    metadata = _artifact_metadata(
        stage="proof_artifact_intake",
        role="proof_artifact_context",
        is_verification_evidence=_proof_is_verification_evidence(proof),
    )
    reviewer_metadata = _artifact_metadata(
        stage="proof_artifact_intake",
        role="reviewer_bundle_summary_context",
        is_verification_evidence=False,
    )
    index_payload = _proof_index_payload(
        run_id=run_id,
        root=root_path,
        proofs=[*existing, proof],
        additional_paths={proof.proof_id: proof_artifact_path},
    )
    persistence = persist_artifacts_with_commit(
        run_id=run_id,
        store=store,
        ledger=ledger,
        artifact_specs=[
            ArtifactWriteSpec(
                proof_artifact_id,
                ArtifactType.REPORT,
                proof,
                "json",
                metadata,
            ),
            ArtifactWriteSpec(
                proof_index_id,
                ArtifactType.REPORT,
                index_payload,
                "json",
                _artifact_metadata(
                    stage="proof_artifact_intake",
                    role="proof_artifact_index_context",
                    is_verification_evidence=False,
                ),
            ),
            ArtifactWriteSpec(
                reviewer_summary_id,
                ArtifactType.REPORT,
                reviewer_summary,
                "json",
                reviewer_metadata,
            ),
            ArtifactWriteSpec(
                f"{reviewer_summary_id}-markdown",
                ArtifactType.REPORT,
                reviewer_summary_markdown,
                "markdown",
                reviewer_metadata,
                filename_stem=reviewer_summary_id,
            ),
        ],
        action_type=ControllerActionType.PROOF_ARTIFACT_INGESTED,
        commit_payload={
            "run_id": run_id,
            "proof_id": proof.proof_id,
            "proof_type": proof.proof_type,
            "checker_status": proof.checker_status,
            "is_verification_evidence": _proof_is_verification_evidence(proof),
            "formal_verification_passed": _proof_is_verification_evidence(proof),
            "publication_ready": False,
            "creates_scientific_validation": False,
            "implies_publication_readiness": False,
            "reviewer_summary_updated": True,
        },
    )
    by_id = {artifact.id: artifact for artifact in persistence.artifacts}
    return ProofArtifactIngestResult(
        run_id=run_id,
        proof=proof,
        persistence=persistence,
        proof_artifact=by_id[proof_artifact_id],
        proof_index_artifact=by_id[proof_index_id],
        reviewer_summary_artifact=by_id[reviewer_summary_id],
        reviewer_summary_markdown_artifact=by_id[f"{reviewer_summary_id}-markdown"],
    )


def ingest_experiment_artifact(
    *,
    run_id: str,
    root: str | Path,
    store: ArtifactStore,
    ledger: ResearchLedger,
    experiment_file: str | Path,
) -> ExperimentArtifactIngestResult:
    """Validate and persist a local experiment artifact without readiness upgrades."""
    root_path = Path(root)
    experiment = load_experiment_artifact(experiment_file)
    _validate_experiment_artifact(
        run_id=run_id,
        root=root_path,
        experiment=experiment,
    )
    existing = _load_experiment_artifacts(run_id=run_id, root=root_path)
    if any(item.experiment_id == experiment.experiment_id for item in existing):
        raise EvidenceArtifactIntakeError(
            "experiment artifact already exists for "
            f"experiment_id={experiment.experiment_id}"
        )

    experiment_artifact_id = (
        f"experiment-artifact-{_safe_suffix(experiment.experiment_id)}"
    )
    experiment_artifact_path = _report_path(run_id, experiment_artifact_id)
    experiment_index_id = (
        "experiment-artifact-index-"
        f"{len(_experiment_index_paths(root_path, run_id)) + 1:04d}"
    )
    reviewer_summary_id = _next_evidence_reviewer_summary_id(root_path, run_id)
    reviewer_summary = build_reviewer_bundle_summary(
        run_id=run_id,
        root=root_path,
        additional_experiment_artifacts=[experiment],
        additional_experiment_artifact_paths=[experiment_artifact_path],
    )
    reviewer_summary_markdown = render_reviewer_bundle_summary_markdown(
        reviewer_summary
    )
    metadata = _artifact_metadata(
        stage="experiment_artifact_intake",
        role="experiment_artifact_context",
        is_verification_evidence=False,
    )
    reviewer_metadata = _artifact_metadata(
        stage="experiment_artifact_intake",
        role="reviewer_bundle_summary_context",
        is_verification_evidence=False,
    )
    index_payload = _experiment_index_payload(
        run_id=run_id,
        root=root_path,
        experiments=[*existing, experiment],
        additional_paths={experiment.experiment_id: experiment_artifact_path},
    )
    persistence = persist_artifacts_with_commit(
        run_id=run_id,
        store=store,
        ledger=ledger,
        artifact_specs=[
            ArtifactWriteSpec(
                experiment_artifact_id,
                ArtifactType.REPORT,
                experiment,
                "json",
                metadata,
            ),
            ArtifactWriteSpec(
                experiment_index_id,
                ArtifactType.REPORT,
                index_payload,
                "json",
                _artifact_metadata(
                    stage="experiment_artifact_intake",
                    role="experiment_artifact_index_context",
                    is_verification_evidence=False,
                ),
            ),
            ArtifactWriteSpec(
                reviewer_summary_id,
                ArtifactType.REPORT,
                reviewer_summary,
                "json",
                reviewer_metadata,
            ),
            ArtifactWriteSpec(
                f"{reviewer_summary_id}-markdown",
                ArtifactType.REPORT,
                reviewer_summary_markdown,
                "markdown",
                reviewer_metadata,
                filename_stem=reviewer_summary_id,
            ),
        ],
        action_type=ControllerActionType.EXPERIMENT_ARTIFACT_INGESTED,
        commit_payload={
            "run_id": run_id,
            "experiment_id": experiment.experiment_id,
            "experiment_type": experiment.experiment_type,
            "status": experiment.status,
            "completed": experiment.status == "completed",
            "publication_ready": False,
            "is_verification_evidence": False,
            "creates_scientific_validation": False,
            "implies_publication_readiness": False,
            "reviewer_summary_updated": True,
        },
    )
    by_id = {artifact.id: artifact for artifact in persistence.artifacts}
    return ExperimentArtifactIngestResult(
        run_id=run_id,
        experiment=experiment,
        persistence=persistence,
        experiment_artifact=by_id[experiment_artifact_id],
        experiment_index_artifact=by_id[experiment_index_id],
        reviewer_summary_artifact=by_id[reviewer_summary_id],
        reviewer_summary_markdown_artifact=by_id[f"{reviewer_summary_id}-markdown"],
    )


def inspect_proof_artifacts(
    *,
    run_id: str,
    root: str | Path = ".",
) -> dict[str, Any]:
    """Inspect persisted proof artifacts without mutation."""
    root_path = Path(root)
    _require_run_path(root_path, run_id)
    proofs = _load_proof_artifacts(run_id=run_id, root=root_path)
    paths = _artifact_paths_for_proofs(root_path, run_id, proofs)
    formal_passed = [proof for proof in proofs if _proof_is_verification_evidence(proof)]
    informal = [proof for proof in proofs if proof.proof_type in _INFORMAL_PROOF_TYPES]
    failed = [
        proof
        for proof in proofs
        if proof.checker_status in {"failed", "inconclusive", "not_checked"}
    ]
    return {
        "run_id": run_id,
        "proof_artifacts_present": bool(proofs),
        "proof_artifact_count": len(proofs),
        "formal_verification_passed_count": len(formal_passed),
        "informal_proof_artifact_count": len(informal),
        "failed_or_inconclusive_proof_artifact_count": len(failed),
        "proof_evidence_gap_present": len(formal_passed) == 0,
        "proof_artifact_paths": paths,
        "proof_artifacts": [proof.model_dump(mode="json") for proof in proofs],
        "publication_ready": False,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
    }


def inspect_experiment_artifacts(
    *,
    run_id: str,
    root: str | Path = ".",
) -> dict[str, Any]:
    """Inspect persisted experiment artifacts without mutation."""
    root_path = Path(root)
    _require_run_path(root_path, run_id)
    experiments = _load_experiment_artifacts(run_id=run_id, root=root_path)
    paths = _artifact_paths_for_experiments(root_path, run_id, experiments)
    completed = [item for item in experiments if item.status == "completed"]
    inconclusive = [item for item in experiments if item.status == "inconclusive"]
    failed = [
        item
        for item in experiments
        if item.status in {"failed", "not_reproducible"}
    ]
    return {
        "run_id": run_id,
        "experiment_artifacts_present": bool(experiments),
        "experiment_artifact_count": len(experiments),
        "completed_experiment_count": len(completed),
        "inconclusive_experiment_count": len(inconclusive),
        "failed_experiment_count": len(failed),
        "experiment_evidence_gap_present": len(completed) == 0,
        "experiment_artifact_paths": paths,
        "experiment_artifacts": [
            experiment.model_dump(mode="json") for experiment in experiments
        ],
        "publication_ready": False,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
        "is_verification_evidence": False,
    }


def _validate_proof_artifact(
    *,
    run_id: str,
    root: Path,
    proof: ProofArtifact,
) -> None:
    if proof.run_id != run_id:
        raise EvidenceArtifactIntakeError("proof artifact run_id does not match")
    expected_evidence = _proof_is_verification_evidence(proof)
    if proof.is_verification_evidence != expected_evidence:
        raise EvidenceArtifactIntakeError(
            "proof artifact verification-evidence flag does not match checker authority"
        )
    if proof.creates_scientific_validation or proof.implies_publication_readiness:
        raise EvidenceArtifactIntakeError(
            "proof artifact cannot create scientific validation or publication readiness"
        )
    if proof.artifact_path_optional:
        _validate_run_artifact_path(
            run_id=run_id,
            root=root,
            artifact_path=proof.artifact_path_optional,
            label="proof artifact path",
        )
    text = _flatten_proof_text(proof)
    if any(marker in text for marker in _LLM_GENERATED_MARKERS):
        raise EvidenceArtifactIntakeError(
            "LLM-generated proof text cannot be ingested as proof evidence"
        )
    for phrase in _FORBIDDEN_AUTHORITY_PHRASES:
        if _contains_unsafe_phrase(text, phrase):
            raise EvidenceArtifactIntakeError(
                "proof artifact claims forbidden publication, novelty, correctness, "
                "or broad validation authority"
            )
    if not expected_evidence and any(
        _contains_unsafe_phrase(text, phrase) for phrase in _PROOF_VERIFICATION_PHRASES
    ):
        raise EvidenceArtifactIntakeError(
            "proof artifact claims verification without a passed checker"
        )
    if (
        proof.proof_type in _FORMAL_PROOF_TYPES
        and proof.checker_status != "passed"
        and proof.is_verification_evidence
    ):
        raise EvidenceArtifactIntakeError(
            "formal proof artifact cannot be verification evidence without a passed checker"
        )


def _validate_experiment_artifact(
    *,
    run_id: str,
    root: Path,
    experiment: ExperimentArtifact,
) -> None:
    if experiment.run_id != run_id:
        raise EvidenceArtifactIntakeError("experiment artifact run_id does not match")
    if (
        experiment.creates_scientific_validation
        or experiment.implies_publication_readiness
        or experiment.is_verification_evidence
    ):
        raise EvidenceArtifactIntakeError(
            "experiment artifact cannot create validation, publication readiness, "
            "or verification evidence"
        )
    for artifact_path in experiment.artifact_paths:
        _validate_run_artifact_path(
            run_id=run_id,
            root=root,
            artifact_path=artifact_path,
            label="experiment artifact path",
        )
    text = _flatten_experiment_text(experiment)
    if any(marker in text for marker in _LLM_GENERATED_MARKERS):
        raise EvidenceArtifactIntakeError(
            "LLM-generated experiment text cannot be ingested as experiment evidence"
        )
    for phrase in (*_FORBIDDEN_AUTHORITY_PHRASES, *_EXPERIMENT_VALIDATION_PHRASES):
        if _contains_unsafe_phrase(text, phrase):
            raise EvidenceArtifactIntakeError(
                "experiment artifact claims forbidden publication, novelty, "
                "correctness, or broad validation authority"
            )


def _validate_run_artifact_path(
    *,
    run_id: str,
    root: Path,
    artifact_path: str,
    label: str,
) -> None:
    run_root_resolved = (root / "runs" / run_id).resolve()
    path = Path(artifact_path)
    full_path = path if path.is_absolute() else root / path
    try:
        full_path.resolve().relative_to(run_root_resolved)
    except ValueError as exc:
        raise EvidenceArtifactIntakeError(
            f"{label} is outside the run root: {artifact_path}"
        ) from exc
    if not full_path.is_file():
        raise EvidenceArtifactIntakeError(f"{label} does not exist: {artifact_path}")


def _load_proof_artifacts(*, run_id: str, root: Path) -> list[ProofArtifact]:
    run_path = root / "runs" / run_id
    if not run_path.is_dir():
        return []
    proofs: list[ProofArtifact] = []
    for path in sorted((run_path / "reports").glob("proof-artifact-*.json")):
        if path.name.startswith("proof-artifact-index-") or path.name.endswith(
            ".meta.json"
        ):
            continue
        try:
            proofs.append(
                ProofArtifact.model_validate_json(path.read_text(encoding="utf-8"))
            )
        except (OSError, ValueError):
            continue
    return sorted(proofs, key=lambda item: item.proof_id)


def _load_experiment_artifacts(*, run_id: str, root: Path) -> list[ExperimentArtifact]:
    run_path = root / "runs" / run_id
    if not run_path.is_dir():
        return []
    experiments: list[ExperimentArtifact] = []
    for path in sorted((run_path / "reports").glob("experiment-artifact-*.json")):
        if path.name.startswith("experiment-artifact-index-") or path.name.endswith(
            ".meta.json"
        ):
            continue
        try:
            experiments.append(
                ExperimentArtifact.model_validate_json(path.read_text(encoding="utf-8"))
            )
        except (OSError, ValueError):
            continue
    return sorted(experiments, key=lambda item: item.experiment_id)


def _proof_index_paths(root: Path, run_id: str) -> list[Path]:
    return sorted(
        path
        for path in (root / "runs" / run_id / "reports").glob(
            "proof-artifact-index-*.json"
        )
        if not path.name.endswith(".meta.json")
    )


def _experiment_index_paths(root: Path, run_id: str) -> list[Path]:
    return sorted(
        path
        for path in (root / "runs" / run_id / "reports").glob(
            "experiment-artifact-index-*.json"
        )
        if not path.name.endswith(".meta.json")
    )


def _next_evidence_reviewer_summary_id(root: Path, run_id: str) -> str:
    existing = sorted(
        path
        for path in (root / "runs" / run_id / "reports").glob(
            "reviewer-bundle-summary-after-evidence-artifacts-*.json"
        )
        if not path.name.endswith(".meta.json")
    )
    return f"reviewer-bundle-summary-after-evidence-artifacts-{len(existing) + 1:04d}"


def _proof_index_payload(
    *,
    run_id: str,
    root: Path,
    proofs: list[ProofArtifact],
    additional_paths: dict[str, str] | None = None,
) -> dict[str, Any]:
    paths = _artifact_paths_for_proofs(root, run_id, proofs, additional_paths)
    formal_passed = sum(1 for proof in proofs if _proof_is_verification_evidence(proof))
    informal = sum(1 for proof in proofs if proof.proof_type in _INFORMAL_PROOF_TYPES)
    return {
        "run_id": run_id,
        "proof_artifact_count": len(proofs),
        "formal_verification_passed_count": formal_passed,
        "informal_proof_artifact_count": informal,
        "proof_artifact_paths": paths,
        "publication_ready": False,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
        "is_verification_evidence": False,
    }


def _experiment_index_payload(
    *,
    run_id: str,
    root: Path,
    experiments: list[ExperimentArtifact],
    additional_paths: dict[str, str] | None = None,
) -> dict[str, Any]:
    paths = _artifact_paths_for_experiments(root, run_id, experiments, additional_paths)
    completed = sum(1 for item in experiments if item.status == "completed")
    inconclusive = sum(1 for item in experiments if item.status == "inconclusive")
    failed = sum(
        1 for item in experiments if item.status in {"failed", "not_reproducible"}
    )
    return {
        "run_id": run_id,
        "experiment_artifact_count": len(experiments),
        "completed_experiment_count": completed,
        "inconclusive_experiment_count": inconclusive,
        "failed_experiment_count": failed,
        "experiment_artifact_paths": paths,
        "publication_ready": False,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
        "is_verification_evidence": False,
    }


def _artifact_paths_for_proofs(
    root: Path,
    run_id: str,
    proofs: list[ProofArtifact],
    additional_paths: dict[str, str] | None = None,
) -> list[str]:
    result: list[str] = []
    for proof in proofs:
        if additional_paths and proof.proof_id in additional_paths:
            result.append(additional_paths[proof.proof_id])
            continue
        artifact_id = f"proof-artifact-{_safe_suffix(proof.proof_id)}"
        path = root / _report_path(run_id, artifact_id)
        if path.is_file():
            result.append(_report_path(run_id, artifact_id))
    return sorted(set(result))


def _artifact_paths_for_experiments(
    root: Path,
    run_id: str,
    experiments: list[ExperimentArtifact],
    additional_paths: dict[str, str] | None = None,
) -> list[str]:
    result: list[str] = []
    for experiment in experiments:
        if additional_paths and experiment.experiment_id in additional_paths:
            result.append(additional_paths[experiment.experiment_id])
            continue
        artifact_id = f"experiment-artifact-{_safe_suffix(experiment.experiment_id)}"
        path = root / _report_path(run_id, artifact_id)
        if path.is_file():
            result.append(_report_path(run_id, artifact_id))
    return sorted(set(result))


def _proof_is_verification_evidence(proof: ProofArtifact) -> bool:
    return proof.proof_type in _FORMAL_PROOF_TYPES and proof.checker_status == "passed"


def _artifact_metadata(
    *,
    stage: str,
    role: str,
    is_verification_evidence: bool,
) -> dict[str, Any]:
    return {
        "stage": stage,
        "artifact_role": role,
        "is_verification_evidence": is_verification_evidence,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
    }


def _flatten_proof_text(proof: ProofArtifact) -> str:
    parts = [
        proof.proof_id,
        proof.proof_type,
        proof.statement,
        proof.artifact_path_optional or "",
        proof.checker_name_optional or "",
        proof.checker_version_optional or "",
        proof.checker_status,
        proof.review_status,
        proof.created_at,
        proof.ingested_at,
    ]
    parts.extend(proof.claim_ids_or_statement_ids)
    parts.extend(proof.limitations)
    return " ".join(parts).casefold()


def _flatten_experiment_text(experiment: ExperimentArtifact) -> str:
    parts = [
        experiment.experiment_id,
        experiment.experiment_type,
        experiment.hypothesis_or_question,
        experiment.status,
        experiment.dataset_name_optional or "",
        experiment.code_commit_hash_optional or "",
        experiment.command_optional or "",
        experiment.result_summary,
        experiment.created_at,
        experiment.ingested_at,
    ]
    parts.extend(experiment.claim_ids_or_section_ids)
    parts.extend(experiment.artifact_paths)
    parts.extend(experiment.limitations)
    parts.extend(str(value) for value in experiment.metrics.values())
    return " ".join(parts).casefold()


def _safe_suffix(value: str) -> str:
    return "".join(
        character if character.isalnum() else "-" for character in value
    ).strip("-")


def _contains_unsafe_phrase(text: str, phrase: str) -> bool:
    remainder = text
    for prefix in (
        "does not imply ",
        "does not establish ",
        "does not claim ",
        "cannot imply ",
        "cannot establish ",
        "cannot claim ",
        "is not ",
        "are not ",
        "without ",
        "no ",
    ):
        remainder = remainder.replace(f"{prefix}{phrase}", "")
    return phrase in remainder


def _report_path(run_id: str, artifact_id: str) -> str:
    return f"runs/{run_id}/reports/{artifact_id}.json"


def _require_run_path(root: Path, run_id: str) -> None:
    if not (root / "runs" / run_id).is_dir():
        raise EvidenceArtifactIntakeError(f"No run directory found for run_id={run_id}.")


__all__ = [
    "EvidenceArtifactIntakeError",
    "ExperimentArtifactIngestResult",
    "ProofArtifactIngestResult",
    "ingest_experiment_artifact",
    "ingest_proof_artifact",
    "inspect_experiment_artifacts",
    "inspect_proof_artifacts",
    "load_experiment_artifact",
    "load_proof_artifact",
]
