"""Deterministic local human-review artifact intake."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from pydantic import ValidationError

from factori.artifacts import ArtifactStore
from factori.full_paper_generation import (
    build_reviewer_bundle_summary,
    render_reviewer_bundle_summary_markdown,
)
from factori.ledger import ResearchLedger
from factori.persistence import (
    ArtifactWriteSpec,
    PersistenceResult,
    persist_artifacts_with_commit,
)
from factori.schemas import (
    ArtifactRef,
    ArtifactType,
    ControllerActionType,
    HumanReviewArtifact,
)

_FORBIDDEN_REVIEW_AUTHORITY_PHRASES = (
    "publication ready",
    "publication-ready",
    "ready for publication",
    "ready to submit",
    "approved for publication",
    "scientifically validated",
    "scientific validation is established",
    "novelty confirmed",
    "novelty validated",
    "proof verified",
    "proof is verified",
    "experiment validated",
    "experiment is validated",
    "correctness validated",
    "correctness is established",
)
_LLM_GENERATED_MARKERS = (
    "as an ai language model",
    "llm-generated",
    "generated by an llm",
    "generated by ai",
)


class HumanReviewIntakeError(RuntimeError):
    """Raised when a human-review artifact cannot be ingested safely."""


@dataclass(frozen=True)
class HumanReviewIngestResult:
    """Persisted human-review artifact and refreshed reviewer summary."""

    run_id: str
    review: HumanReviewArtifact
    persistence: PersistenceResult
    review_artifact: ArtifactRef
    review_summary_artifact: ArtifactRef
    reviewer_summary_artifact: ArtifactRef
    reviewer_summary_markdown_artifact: ArtifactRef


def load_human_review_artifact(review_file: str | Path) -> HumanReviewArtifact:
    """Load and structurally validate one local human-review JSON file."""
    path = Path(review_file)
    try:
        return HumanReviewArtifact.model_validate_json(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise HumanReviewIntakeError(f"Unable to read human review file: {path}") from exc
    except ValidationError as exc:
        raise HumanReviewIntakeError(f"Invalid human review artifact: {exc}") from exc


def ingest_human_review(
    *,
    run_id: str,
    root: str | Path,
    store: ArtifactStore,
    ledger: ResearchLedger,
    review_file: str | Path,
) -> HumanReviewIngestResult:
    """Validate and persist a local human-review artifact without evidence upgrades."""
    root_path = Path(root)
    if any(
        commit.action_type == ControllerActionType.HUMAN_REVIEW_INGESTED
        for commit in ledger.list_commits(run_id)
    ):
        raise HumanReviewIntakeError("human review artifact already exists for this run")
    review = load_human_review_artifact(review_file)
    _validate_human_review(run_id=run_id, root=root_path, review=review)
    review_summary_markdown = render_human_review_summary_markdown(review)
    reviewer_summary = build_reviewer_bundle_summary(
        run_id=run_id,
        root=root_path,
        human_review_artifact=review,
    )
    reviewer_summary_markdown = render_reviewer_bundle_summary_markdown(
        reviewer_summary
    )
    metadata = {
        "stage": "human_review_intake",
        "artifact_role": "human_review_occurrence_context",
        "is_verification_evidence": False,
        "creates_scientific_validation": False,
        "implies_publication_readiness": False,
    }
    reviewer_metadata = {
        **metadata,
        "artifact_role": "reviewer_bundle_summary_context",
    }
    persistence = persist_artifacts_with_commit(
        run_id=run_id,
        store=store,
        ledger=ledger,
        artifact_specs=[
            ArtifactWriteSpec(
                "human-review-artifact",
                ArtifactType.REPORT,
                review,
                "json",
                metadata,
            ),
            ArtifactWriteSpec(
                "human-review-summary",
                ArtifactType.REPORT,
                review_summary_markdown,
                "markdown",
                metadata,
            ),
            ArtifactWriteSpec(
                "reviewer-bundle-summary-after-human-review",
                ArtifactType.REPORT,
                reviewer_summary,
                "json",
                reviewer_metadata,
            ),
            ArtifactWriteSpec(
                "reviewer-bundle-summary-after-human-review-markdown",
                ArtifactType.REPORT,
                reviewer_summary_markdown,
                "markdown",
                reviewer_metadata,
                filename_stem="reviewer-bundle-summary-after-human-review",
            ),
        ],
        action_type=ControllerActionType.HUMAN_REVIEW_INGESTED,
        commit_payload={
            "run_id": run_id,
            "review_id": review.review_id,
            "review_status": review.review_status,
            "blocking_concerns": len(review.blocking_concerns),
            "requested_changes": len(review.requested_changes),
            "publication_ready": False,
            "reviewer_summary_updated": True,
            "is_verification_evidence": False,
            "creates_scientific_validation": False,
            "implies_publication_readiness": False,
        },
    )
    by_id = {artifact.id: artifact for artifact in persistence.artifacts}
    return HumanReviewIngestResult(
        run_id=run_id,
        review=review,
        persistence=persistence,
        review_artifact=by_id["human-review-artifact"],
        review_summary_artifact=by_id["human-review-summary"],
        reviewer_summary_artifact=by_id[
            "reviewer-bundle-summary-after-human-review"
        ],
        reviewer_summary_markdown_artifact=by_id[
            "reviewer-bundle-summary-after-human-review-markdown"
        ],
    )


def inspect_human_review(
    *,
    run_id: str,
    root: str | Path = ".",
) -> dict[str, object]:
    """Inspect a persisted local human-review artifact without mutation."""
    root_path = Path(root)
    run_path = root_path / "runs" / run_id
    if not run_path.is_dir():
        raise HumanReviewIntakeError(f"No run directory found for run_id={run_id}.")
    review_path = run_path / "reports" / "human-review-artifact.json"
    if not review_path.is_file():
        raise HumanReviewIntakeError(
            f"No human review artifact found for run_id={run_id}."
        )
    review = load_human_review_artifact(review_path)
    return {
        **review.model_dump(mode="json"),
        "human_review_artifact_present": True,
        "human_review_artifact_path": review_path.relative_to(root_path).as_posix(),
        "human_review_blocking_concern_count": len(review.blocking_concerns),
        "human_review_requested_change_count": len(review.requested_changes),
        "publication_ready": False,
    }


def render_human_review_summary_markdown(review: HumanReviewArtifact) -> str:
    """Render a compact non-evidence human-review summary."""
    lines = [
        "# Human Review Summary",
        "",
        f"Run ID: `{review.run_id}`",
        f"Review ID: `{review.review_id}`",
        f"Reviewer role: `{review.reviewer_role}`",
        f"Review status: `{review.review_status}`",
        f"Reviewed at: `{review.reviewed_at}`",
        f"Blocking concerns: `{len(review.blocking_concerns)}`",
        f"Requested changes: `{len(review.requested_changes)}`",
        f"Recommended next action: `{review.recommended_next_action}`",
        "",
        "## Checklist",
        *[f"- {item}" for item in review.checklist_items],
        "",
        "## Blocking Concerns",
    ]
    lines.extend(f"- {item}" for item in review.blocking_concerns or ["none"])
    lines.extend(["", "## Requested Changes"])
    lines.extend(f"- {item}" for item in review.requested_changes or ["none"])
    lines.extend(
        [
            "",
            "## Boundary",
            "- Human review records that a human review occurred.",
            (
                "- Human review does not establish proof, experiment validation, "
                "novelty, correctness, or publication readiness."
            ),
            "- publication_ready: false",
            "- creates_scientific_validation: false",
            "- implies_publication_readiness: false",
            "- is_verification_evidence: false",
            "",
        ]
    )
    return "\n".join(lines)


def _validate_human_review(
    *,
    run_id: str,
    root: Path,
    review: HumanReviewArtifact,
) -> None:
    if review.run_id != run_id:
        raise HumanReviewIntakeError("human review run_id does not match requested run_id")
    if not review.reviewer_is_human or review.llm_generated:
        raise HumanReviewIntakeError("LLM-generated or non-human review cannot be ingested")
    if review.review_status == "not_reviewed":
        raise HumanReviewIntakeError("human review status must record a completed review")
    if not review.checklist_items:
        raise HumanReviewIntakeError("human review checklist must not be empty")
    if not review.reviewer_attestation.strip():
        raise HumanReviewIntakeError("human review attestation is required")
    if (
        review.creates_scientific_validation
        or review.implies_publication_readiness
        or review.is_verification_evidence
    ):
        raise HumanReviewIntakeError(
            "human review cannot create validation, publication readiness, or verification evidence"
        )
    _validate_reviewed_artifact_paths(run_id=run_id, root=root, review=review)
    text = _flatten_review_text(review, include_requested_changes=False)
    for phrase in _FORBIDDEN_REVIEW_AUTHORITY_PHRASES:
        if phrase in text:
            raise HumanReviewIntakeError(
                "human review claims forbidden publication, validation, novelty, "
                "proof, experiment, or correctness authority"
            )
    if any(marker in text for marker in _LLM_GENERATED_MARKERS):
        raise HumanReviewIntakeError("human review appears to be LLM-generated")


def _validate_reviewed_artifact_paths(
    *,
    run_id: str,
    root: Path,
    review: HumanReviewArtifact,
) -> None:
    run_root_resolved = (root / "runs" / run_id).resolve()
    for artifact_path in review.reviewed_artifact_paths:
        path = Path(artifact_path)
        full_path = path if path.is_absolute() else root / path
        try:
            full_path.resolve().relative_to(run_root_resolved)
        except ValueError as exc:
            raise HumanReviewIntakeError(
                f"reviewed artifact path is outside the run root: {artifact_path}"
            ) from exc
        if not full_path.is_file():
            raise HumanReviewIntakeError(
                f"reviewed artifact path does not exist: {artifact_path}"
            )


def _flatten_review_text(
    review: HumanReviewArtifact,
    *,
    include_requested_changes: bool = True,
) -> str:
    parts: list[str] = [
        review.review_id,
        review.reviewer_name_optional or "",
        review.reviewer_role,
        review.review_status,
        review.reviewed_at,
        review.recommended_next_action,
        review.reviewer_attestation,
    ]
    parts.extend(review.reviewed_artifact_paths)
    parts.extend(review.checklist_items)
    parts.extend(review.blocking_concerns)
    parts.extend(review.non_blocking_comments)
    if include_requested_changes:
        parts.extend(review.requested_changes)
    parts.extend(review.accepted_limitations)
    return " ".join(parts).casefold()


__all__ = [
    "HumanReviewIngestResult",
    "HumanReviewIntakeError",
    "ingest_human_review",
    "inspect_human_review",
    "load_human_review_artifact",
    "render_human_review_summary_markdown",
]
